# Generated by Django 4.1.2 on 2022-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('session', models.CharField(max_length=20, null=True)),
                ('first', models.TextField(null=True)),
                ('second', models.TextField(null=True)),
                ('third', models.TextField(null=True)),
                ('fourth', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
    ]
